name: Django-app workflow

on: [push]

jobs: 
  tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        # обновление pip
        python -m pip install --upgrade pip
        # установка flake8 и его плагинов
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # установка зависимостей
        pip install -r requirements.txt
    - name: Test with flake8 and django tests
      run: |
        # start a project check on flake8
        python -m flake8
        # go to the folder containing manage.py -
        # <root_project_folder>/<project_folder>/manage.py
        cd infra_project/
        # run tests written by the dev
        python manage.py test
      